# Generated by Django 5.2.4 on 2025-10-22 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('database_name', models.CharField(blank=True, help_text='Nome do banco de dados específico da empresa', max_length=100, verbose_name='Nome do Banco de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('trial', 'Trial'), ('basica', 'Básica'), ('profissional', 'Profissional'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Tipo de Licença')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('max_funcionarios', models.PositiveIntegerField(default=10, help_text='Número máximo de funcionários permitidos', verbose_name='Máximo de Funcionários')),
                ('max_usuarios', models.PositiveIntegerField(default=5, help_text='Número máximo de usuários do sistema', verbose_name='Máximo de Usuários')),
                ('permite_banco_horas', models.BooleanField(default=True, verbose_name='Permite Banco de Horas')),
                ('permite_ponto_eletronico', models.BooleanField(default=True, verbose_name='Permite Ponto Eletrônico')),
                ('permite_relatorios_avancados', models.BooleanField(default=False, verbose_name='Permite Relatórios Avançados')),
                ('permite_integracao_api', models.BooleanField(default=False, verbose_name='Permite Integração API')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'db_table': 'licenca',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicencaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.licenca', verbose_name='Licença')),
            ],
            options={
                'verbose_name': 'Histórico de Licença',
                'verbose_name_plural': 'Histórico de Licenças',
                'db_table': 'licenca_historico',
                'ordering': ['-created_at'],
            },
        ),
    ]
