# Generated by Django 5.2.4 on 2025-10-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID da empresa no banco master', null=True, verbose_name='ID da Empresa'),
        ),
    ]
