# Generated by Django 2.2.28 on 2025-07-22 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
            ],
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da folga')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='Motivo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.Funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
                'unique_together': {('funcionario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.Funcionario', verbose_name='Funcionário')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.Turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
