# Generated by Django 2.2.28 on 2025-07-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaPredefinida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da escala')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('horas_trabalho', models.PositiveIntegerField(verbose_name='Horas de trabalho')),
                ('horas_descanso', models.PositiveIntegerField(verbose_name='Horas de descanso')),
            ],
        ),
    ]
