# Generated by Django 5.2.4 on 2025-10-21 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalator', '0004_alter_escala_id_alter_escalapredefinida_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['-data'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterModelOptions(
            name='escalapredefinida',
            options={'verbose_name': 'Escala Predefinida', 'verbose_name_plural': 'Escalas Predefinidas'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='escala',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.001037037037037037, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='descanso',
            field=models.BooleanField(default=False, verbose_name='Dia de descanso (DSR)'),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
        migrations.AddField(
            model_name='escala',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de início'),
        ),
        migrations.AddField(
            model_name='escala',
            name='pausa_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Pausa em minutos'),
        ),
        migrations.AddField(
            model_name='escala',
            name='tipo_escala',
            field=models.CharField(choices=[('normal', 'Normal'), ('12x36', '12x36'), ('noturna', 'Noturna'), ('extra', 'Hora Extra')], default='normal', max_length=20, verbose_name='Tipo de escala'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.001037037037037037, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escala',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalator.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carga_diaria_max', models.PositiveIntegerField(default=480, verbose_name='Carga diária máxima (minutos)')),
                ('carga_semanal_max', models.PositiveIntegerField(default=2640, verbose_name='Carga semanal máxima (minutos)')),
                ('extra_diaria_cap', models.PositiveIntegerField(default=120, verbose_name='Limite diário de horas extras (minutos)')),
                ('banco_horas_prazo_meses', models.PositiveIntegerField(default=12, verbose_name='Prazo banco de horas (meses)')),
                ('permite_12x36', models.BooleanField(default=False, verbose_name='Permite escala 12x36')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='Data e hora')),
                ('tipo_registro', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('pausa_inicio', 'Início da Pausa'), ('pausa_fim', 'Fim da Pausa')], max_length=20, verbose_name='Tipo de registro')),
                ('localizacao_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('localizacao_lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalator.escala', verbose_name='Escala')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BancoHoras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_referencia', models.DateField(verbose_name='Data de referência')),
                ('credito_minutos', models.IntegerField(default=0, verbose_name='Crédito (minutos)')),
                ('debito_minutos', models.IntegerField(default=0, verbose_name='Débito (minutos)')),
                ('saldo_minutos', models.IntegerField(default=0, verbose_name='Saldo (minutos)')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('compensado', models.BooleanField(default=False, verbose_name='Compensado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalator.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Banco de Horas',
                'verbose_name_plural': 'Banco de Horas',
                'ordering': ['-data_referencia'],
                'unique_together': {('funcionario', 'data_referencia')},
            },
        ),
    ]
