# Generated by Django 5.2.4 on 2025-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalator', '0005_configuracaosistema_alter_escala_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancohoras',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escala',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
