# Generated by Django 5.2.4 on 2025-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalator', '0006_alter_bancohoras_id_alter_contrato_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folga',
            options={'ordering': ['-data'], 'verbose_name': 'Folga', 'verbose_name_plural': 'Folgas'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='escalapredefinida',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='bancohoras',
            table='banco_horas',
        ),
        migrations.AlterModelTable(
            name='configuracaosistema',
            table='configuracao_sistema',
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
        migrations.AlterModelTable(
            name='escala',
            table='escala',
        ),
        migrations.AlterModelTable(
            name='folga',
            table='folga',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
        migrations.AlterModelTable(
            name='ponto',
            table='ponto',
        ),
    ]
